name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - cudatoolkit=11.8
  - plyfile
  - tqdm
  - pip:
      - torch==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - torchaudio==2.1.0
      - opencv-python
      - joblib
      - --extra-index-url https://download.pytorch.org/whl/cu118
